kind: pipeline
name: encryptor-node-ci

steps:
  - name: slack-build-start
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: encryptor
      template: >
          {{build.event}} to `{{ lowercase build.branch }}` by *{{ build.author }}* -> {{ build.link }}

  - name: lint & tests
    image: node:latest
    commands:
    - npm i --silent
    - npm run lint
    - npm run test
    when:
      event: [ pull_request ]
      branch: master

  - name: build
    image: node:latest
    commands:
    - npm i --silent
    - npm run build
    when:
      event: push
      branch: master

  - name: npm
    image: plugins/npm
    settings:
      email:
        from_secret: npm_email
      username:
        from_secret: npm_username
      password:
        from_secret: npm_password
    when:
      event: push
      branch: master

  - name: slack-build-finished
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: encryptor
      template: >
        {{#success build.status}}
          {{build.event}} to `{{ lowercase build.branch }}` succeeded. Good job *{{ build.author }}*.
        {{else}}
          {{build.event}} to `{{ lowercase build.branch }}` failed. Please by *{{ build.author }}* fix me -> {{ build.link }}
        {{/success}}
    when:
      event: [ push, pull_request ]
      branch: master
